<?php
  function actualizarEjecutores()
  {
	   $link = Conectar();


	   $sql = "UPDATE Programacion_Maniobras_Unificado SET Empresa = 'Mejía Acevedo' WHERE 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'CARLOS VILL%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'HUGO GRACIA%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'JAIRO VALEN%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'JAVIER MART%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'JOSÉ CUERVO%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'LEIDER MANC%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'MARYOI LOAI%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'MAURICIO BA%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'ROBERTO GIL%';";

	   $link->query(utf8_decode($sql));

	   $sql ="UPDATE Programacion_Maniobras_Unificado SET Empresa = 'Ingelectrica' WHERE 
	    ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'Andrés Feli%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'HERNÁN DARÍ%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'HUGO FERLEY%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'JORGE IGNAC%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'JORGE LEONA%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'PEDRO ANTON%' OR 
	ENCARGADO_CON_No_DE_DIVISA_EN_CAMPO LIKE 'RUBEN DARIO%';";

	$link->query(utf8_decode($sql));
  }
?>